name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    
    - name: Install dependencies
      run: |
        cd playwright
        npm install

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    
    - name: Run Playwright tests
      env:
        DASHBOARD_PASSWORD: ${{ secrets.DASHBOARD_PASSWORD }}
        DASHBOARD_MAIL: ${{ secrets.DASHBOARD_MAIL }}
        DASHBOARD_WEBURL: ${{ secrets.DASHBOARD_WEBURL }}
      run: |
        echo "Running Playwright tests..."
        cd playwright
        npx playwright test

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
